### ISSUE TITLE
Set bonus

### ISSUE THREAD

**Issue by sargon64** [velvet-moe/InfernalMobs#21]

**Comment by ChecksumDev** [comment]
A pseudo-config mock up for this could be something like this
```yml
  - archers_vest:
      name: "§cArchers Vest"
      item: "IRON_CHESTPLATE"
      type: "ARMOR"
      group: "ARCHERS" # or set?
      weight: 10
      lore:
        - "§4Take an arrow to the knee!"
      enchantments:
        - PROJECTILE_PROTECTION:
            level: 10
```

Then you'd likely just group the items in Kotlin by the `group/set` string, only applying effects if `active_set_items = active_set_length`.
